# Generated by Django 5.2.4 on 2025-09-15 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('ride_datetime', models.DateTimeField()),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=10)),
                ('seats_available', models.PositiveIntegerField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
